"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ex$ic-$(!_u8%xoe$ubt7h!ub^d_5yt3q=75%22t0p3gz_mj('

# 初始化环境变量
env = environ.Env(
    DEBUG=(bool, False),
    DB_TYPE = (str, "mysql"),
    DB_MYSQL_HOST = (str, "localhost"),
    DB_MYSQL_NAME = (str, ""),
    DB_MYSQL_USER = (str, "root"),
    DB_MYSQL_PASSWORD = (str, ""),
    DB_MYSQL_PORT = (int, 3306),
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 读取.env文件
environ.Env.read_env(Path.joinpath(BASE_DIR, ".env"))

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False
# 从.env文件中读取DEBUG的值 
DEBUG = env("DEBUG")
# ALLOWED_HOSTS = []
# 允许访问的HOST，*表示所有，也可以设置为127.0.0.1或者localhost来表示仅允许本地HOST访问。+  
# # 更多说明可参阅 https://docs.djangoproject.com/zh-hans/5.0/ref/settings/#allowed-hosts
ALLOWED_HOSTS = ["*"] # 关闭 DEBUG 设置为['*']表示允许任何HOST访问来源。

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC' # 时区设置为UTC 目的是让所有时间都以UTC时间表示，这样可以避免不同地区的时间差异问题
# 如果需要使用本地时间，可以将TIME_ZONE设置为本地时区，例如'Asia/Shanghai'
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

# USE_TZ = True # 是否使用时区，默认为True 
USE_TZ = False # 如果要求Django以本地时间入库，可以设置为False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
